// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function RepoList(Props) {
  return React.createElement("div", {
              className: "p-5"
            }, React.createElement("div", undefined, "Hey~ I ❤️ ReScript."), React.createElement("input", {
                  className: "border-solid border rounded-md",
                  type: "text"
                }));
}

var make = RepoList;

export {
  make ,
}
/* react Not a pure module */
