// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function RepoList$default(Props) {
  return React.createElement("div", {
              className: "p-5"
            }, React.createElement("div", undefined, "Hey??"), React.createElement("input", {
                  className: "border-solid border rounded-md",
                  type: "text"
                }));
}

var $$default = RepoList$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
