// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Test(Props) {
  return React.createElement("div", {
              className: "p-5"
            }, "I'm a test component?! HMR works!");
}

function Test$Test(Props) {
  return React.createElement("div", {
              className: "p-5"
            }, "I'm a test component?! HMR works!!");
}

var Test$1 = {
  make: Test$Test
};

var make = Test;

export {
  make ,
  Test$1 as Test,
}
/* react Not a pure module */
